import Head from 'next/head';
import React from 'react';
import Banner from '../components/Banner';
import Header from '../components/Header';
import Row from '../components/Row';
import { RowData } from '../typings';
import fetchMovieData from '../util/fetchMovieData';

interface Props {
  data: RowData[];
  randomNumb: number;
}

const Home = ({ data, randomNumb }: Props) => {
  const [headerBlack, setHeaderBlack] = React.useState(true);
  return (
    <div className="relative text-[#e5e5e5]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerBlack={headerBlack} />
      <Banner movieInfo={data[0].results[randomNumb]} />
      <div className="absolute z-40 w-full overflow-hidden top-[40vw] left-0">
        {data.map((rowData, index) => (
          <Row
            key={index}
            rowData={rowData}
            rowIndex={index}
            setHeaderBlack={setHeaderBlack}
          />
        ))}
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const data = await fetchMovieData();

  const randomNumb = Math.floor(Math.random() * 19);

  return {
    props: {
      data: data,
      randomNumb: randomNumb,
    },
  };
}

export default Home;
