import Head from 'next/head';
import Banner from '../components/Banner';
import Header from '../components/Header';
import Row from '../components/Row';
import { RowData } from '../typings';
import fetchMovieData from '../util/fetchMovieData';

interface Props {
  data: RowData[];
}

const Home = ({ data }: Props) => {
  return (
    <div className="relative h-screen text-[#e5e5e5]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner bannerInfo={data[0].results} />
      <div className="absolute z-20 w-full overflow-hidden top-[40vw] left-0">
        {data.map((rowData, index) => (
          <Row key={index} rowData={rowData} index={index} />
        ))}
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const data = await fetchMovieData();

  return {
    props: {
      data: data,
    },
  };
}

export default Home;
